### ISSUE TITLE
컨테이너 끼리 연결을 위해서 link 옵션 대신 네트워크 이용

### ISSUE THREAD

**Issue by baram204** [baram204/Machine-Learning-With-Go#10]
https://docs.docker.com/network/bridge/#manage-a-user-defined-bridge

엉?

https://docs.docker.com/compose/networking/

같은 컴포즈 파일 내에서 정의한 서비스 끼리는 이미 같은 네트워크를 사용하고...

서비스 명으로 호스트를 연결할 수 있단다. 신기한데?

**Comment by baram204** [comment]
```
version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres
    ports:
      - "8001:5432"
```

web 컨테이너에서 db 컨테이너 접근 시는 컨테이너 포트를 사용하고

`postgres://db:5432`

외부에서 db 컨테이너 접근 시 정의한 호스트 컨테이너 사용한다.

`postgres://{DOCKER_IP}:8001`

이 프로젝트에서는 도커 머신을 사용 중이고.. 스웜 ip 겠지.
